---
abstract: 'Losslessly fix JPEG orientation'
author:
  - '唐鳳 <cpan@audreyt.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Image::JpegTran::AutoRotate
name: Image-JpegTran-AutoRotate
no_index:
  directory:
    - inc
    - t
requires:
  Image::ExifTool: 0
  Image::JpegTran: 0
  perl: 5.6.0
resources:
  homepage: https://github.com/audreyt/image-jpegtran-auto/tree
  repository: git://github.com/audreyt/image-jpegtran-auto.git
version: 0.01
